name: Mirror Github org repos to Gitee
on:
  push:
    branches:
      - main

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/kunpengcompute
          dst: gitee/kunpengcompute
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
