name: Mirror to Gitee
on: [push]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: Yikun/actions-mirror@v0.4.9
        with:
          src: 'git@github.com:DDL08/bank-management-system.git'
          dst: 'git@gitee.com:lidd8/bank-management-system.git'
          static_list: 'main'
          ssh_private_key: ${{ secrets.GITEE_PRIVATE_KEY }}
