name: Mirror to Gitee

on: [push]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror GitHub to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/DDL08/bank-management-system
          dst: gitee/lidd8/bank-management-system
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
